// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujyxeZbyHHrV05LH_tDFLuP12_Mw9P_0',
    appId: '1:904646289214:web:fcdc2bc9fc8552dd072e6f',
    messagingSenderId: '904646289214',
    projectId: 'gymsocial-70e88',
    authDomain: 'gymsocial-70e88.firebaseapp.com',
    storageBucket: 'gymsocial-70e88.appspot.com',
    measurementId: 'G-18F1HV9QFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ6NAhMbnn-tm_dP9lPNUT2Ue0pyFWGww',
    appId: '1:904646289214:android:aa2056bc0d766401072e6f',
    messagingSenderId: '904646289214',
    projectId: 'gymsocial-70e88',
    storageBucket: 'gymsocial-70e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP75FN94GjwTrvp6zmpLVM7ji8qO-wMkw',
    appId: '1:904646289214:ios:eea40c0dbe565a10072e6f',
    messagingSenderId: '904646289214',
    projectId: 'gymsocial-70e88',
    storageBucket: 'gymsocial-70e88.appspot.com',
    iosBundleId: 'com.gymsocial.gymsocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP75FN94GjwTrvp6zmpLVM7ji8qO-wMkw',
    appId: '1:904646289214:ios:eea40c0dbe565a10072e6f',
    messagingSenderId: '904646289214',
    projectId: 'gymsocial-70e88',
    storageBucket: 'gymsocial-70e88.appspot.com',
    iosBundleId: 'com.gymsocial.gymsocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDujyxeZbyHHrV05LH_tDFLuP12_Mw9P_0',
    appId: '1:904646289214:web:f3d16e2de8d35519072e6f',
    messagingSenderId: '904646289214',
    projectId: 'gymsocial-70e88',
    authDomain: 'gymsocial-70e88.firebaseapp.com',
    storageBucket: 'gymsocial-70e88.appspot.com',
    measurementId: 'G-H7WCNNVTQN',
  );
}
